/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisadcont.Forms.Panels;

/**
 *
 * @author sisadcont
 */
public class V_Empleados_Datos extends javax.swing.JPanel {

    /**
     * Creates new form V_Empleados_Datos
     */
    public V_Empleados_Datos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_id = new principal.MaterialTextField();
        txt_nombres = new principal.MaterialTextField();
        txt_primer_apellido = new principal.MaterialTextField();
        txt_segundo_apellido = new principal.MaterialTextField();
        txt_fecha_de_entrada = new principal.MaterialTextField();
        txt_direccion = new principal.MaterialTextField();
        txt_telefono = new principal.MaterialTextField();
        txt_celular = new principal.MaterialTextField();
        txt_correo = new principal.MaterialTextField();
        txt_cedula = new principal.MaterialTextField();
        txt_fecha_nacimiento = new principal.MaterialTextField();
        txt_cargo = new principal.MaterialTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        cb_estado_civil = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        femenino_radio_button = new javax.swing.JRadioButton();
        masculino_radio_button = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imagen_opciones_combobox = new javax.swing.JComboBox<>();
        subir_foto_btn = new principal.MaterialButton();
        quitar_btn = new principal.MaterialButton();
        portapapel_btn = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(34, 94, 156));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRES:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 92, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRIMER APELLIDO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 129, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEGUNDO APELLIDO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 166, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA DE ENTRADA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 203, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DIRECCION:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELEFONO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 277, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CELULAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 314, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CORREO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 351, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ESTADO CIVIL:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 388, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CEDULA:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 425, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 462, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CARGO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 499, -1, -1));

        txt_id.setBackground(new java.awt.Color(34, 94, 156));
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 55, 65, -1));

        txt_nombres.setBackground(new java.awt.Color(34, 94, 156));
        txt_nombres.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 92, 251, -1));

        txt_primer_apellido.setBackground(new java.awt.Color(34, 94, 156));
        txt_primer_apellido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_primer_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 129, 251, -1));

        txt_segundo_apellido.setBackground(new java.awt.Color(34, 94, 156));
        txt_segundo_apellido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_segundo_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 166, 251, -1));

        txt_fecha_de_entrada.setBackground(new java.awt.Color(34, 94, 156));
        txt_fecha_de_entrada.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_fecha_de_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 203, 251, -1));

        txt_direccion.setBackground(new java.awt.Color(34, 94, 156));
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 240, 251, -1));

        txt_telefono.setBackground(new java.awt.Color(34, 94, 156));
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 277, 251, -1));

        txt_celular.setBackground(new java.awt.Color(34, 94, 156));
        txt_celular.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 314, 251, -1));

        txt_correo.setBackground(new java.awt.Color(34, 94, 156));
        txt_correo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 351, 251, -1));

        txt_cedula.setBackground(new java.awt.Color(34, 94, 156));
        txt_cedula.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 425, 110, -1));

        txt_fecha_nacimiento.setBackground(new java.awt.Color(34, 94, 156));
        txt_fecha_nacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 462, 110, -1));

        txt_cargo.setBackground(new java.awt.Color(34, 94, 156));
        txt_cargo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 499, 110, -1));

        jCheckBox1.setBackground(new java.awt.Color(34, 94, 156));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ACTIVO");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        cb_estado_civil.setBackground(new java.awt.Color(34, 94, 156));
        cb_estado_civil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_estado_civil.setForeground(new java.awt.Color(255, 255, 255));
        cb_estado_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_estado_civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(34, 94, 156));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SEXO");

        femenino_radio_button.setBackground(new java.awt.Color(34, 94, 156));
        femenino_radio_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        femenino_radio_button.setForeground(new java.awt.Color(255, 255, 255));
        femenino_radio_button.setText("FEMENINO");

        masculino_radio_button.setBackground(new java.awt.Color(34, 94, 156));
        masculino_radio_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        masculino_radio_button.setForeground(new java.awt.Color(255, 255, 255));
        masculino_radio_button.setText("MASCULINO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(femenino_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino_radio_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(femenino_radio_button)
                .addGap(18, 18, 18)
                .addComponent(masculino_radio_button)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 120, 140));

        jPanel3.setBackground(new java.awt.Color(34, 94, 156));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(34, 94, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        imagen_opciones_combobox.setBackground(new java.awt.Color(34, 94, 156));
        imagen_opciones_combobox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imagen_opciones_combobox.setForeground(new java.awt.Color(255, 255, 255));
        imagen_opciones_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expandir", "Item 2", "Item 3", "Item 4" }));

        subir_foto_btn.setBackground(new java.awt.Color(250, 106, 18));
        subir_foto_btn.setForeground(new java.awt.Color(255, 255, 255));
        subir_foto_btn.setText("SUBIR FOTO");

        quitar_btn.setBackground(new java.awt.Color(250, 106, 18));
        quitar_btn.setForeground(new java.awt.Color(255, 255, 255));
        quitar_btn.setText("QUITAR");

        portapapel_btn.setBackground(new java.awt.Color(250, 106, 18));
        portapapel_btn.setForeground(new java.awt.Color(255, 255, 255));
        portapapel_btn.setText("PORTAPAPEL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(subir_foto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(quitar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagen_opciones_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(portapapel_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(imagen_opciones_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(portapapel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subir_foto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_estado_civil;
    private javax.swing.JRadioButton femenino_radio_button;
    private javax.swing.JComboBox<String> imagen_opciones_combobox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton masculino_radio_button;
    private principal.MaterialButton portapapel_btn;
    private principal.MaterialButton quitar_btn;
    private principal.MaterialButton subir_foto_btn;
    private principal.MaterialTextField txt_cargo;
    private principal.MaterialTextField txt_cedula;
    private principal.MaterialTextField txt_celular;
    private principal.MaterialTextField txt_correo;
    private principal.MaterialTextField txt_direccion;
    private principal.MaterialTextField txt_fecha_de_entrada;
    private principal.MaterialTextField txt_fecha_nacimiento;
    private principal.MaterialTextField txt_id;
    private principal.MaterialTextField txt_nombres;
    private principal.MaterialTextField txt_primer_apellido;
    private principal.MaterialTextField txt_segundo_apellido;
    private principal.MaterialTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
