/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisadcont.Forms.Panels;

import sisadcont.Forms.P_Principal;

/**
 *
 * @author sisadcont
 */
public class V_Fact extends javax.swing.JPanel {

    /**
     * Creates new form V_Fact
     */
    public V_Fact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1020, 740));
        setMinimumSize(new java.awt.Dimension(1020, 740));
        setPreferredSize(new java.awt.Dimension(1020, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MANTE.png"))); // NOI18N
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 700, 310));

        textField1.setText("textField1");
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 230, 40));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel31;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
