/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisadcont.Forms.Panels;

/**
 *
 * @author sisadcont
 */
public class V_Novedades extends javax.swing.JPanel {

    /**
     * Creates new form V_Novedades
     */
    public V_Novedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new principal.MaterialTextField();
        txt_descripcion = new principal.MaterialTextField();
        jLabel3 = new javax.swing.JLabel();
        combobox_ingreso = new javax.swing.JComboBox<>();
        checkbox_reservada = new javax.swing.JCheckBox();
        checkbox_calcularAFP = new javax.swing.JCheckBox();
        checkbox_calcularSFS = new javax.swing.JCheckBox();
        checkbox_calcularISR = new javax.swing.JCheckBox();
        btnSalir = new principal.MaterialButton();
        btnAceptar1 = new principal.MaterialButton();

        setBackground(new java.awt.Color(34, 94, 156));
        setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPCION");

        txt_id.setBackground(new java.awt.Color(34, 94, 156));
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_id.setSelectionColor(new java.awt.Color(250, 106, 18));

        txt_descripcion.setBackground(new java.awt.Color(34, 94, 156));
        txt_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        txt_descripcion.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_descripcion.setSelectionColor(new java.awt.Color(250, 106, 18));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIPO");

        combobox_ingreso.setBackground(new java.awt.Color(34, 94, 156));
        combobox_ingreso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combobox_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        combobox_ingreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Item 2", "Item 3", "Item 4" }));

        checkbox_reservada.setBackground(new java.awt.Color(34, 94, 156));
        checkbox_reservada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkbox_reservada.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_reservada.setText("Reservada");

        checkbox_calcularAFP.setBackground(new java.awt.Color(34, 94, 156));
        checkbox_calcularAFP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkbox_calcularAFP.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_calcularAFP.setText("Calcula AFP");

        checkbox_calcularSFS.setBackground(new java.awt.Color(34, 94, 156));
        checkbox_calcularSFS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkbox_calcularSFS.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_calcularSFS.setText("Calcula Seguro Familiar de Salud (SFS)");

        checkbox_calcularISR.setBackground(new java.awt.Color(34, 94, 156));
        checkbox_calcularISR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkbox_calcularISR.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_calcularISR.setText("Calcula Renta (ISR)");

        btnSalir.setBackground(new java.awt.Color(250, 106, 18));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");

        btnAceptar1.setBackground(new java.awt.Color(250, 106, 18));
        btnAceptar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar1.setText("ACEPTAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbox_reservada)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkbox_calcularAFP)
                            .addComponent(checkbox_calcularSFS)
                            .addComponent(checkbox_calcularISR))
                        .addContainerGap(139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combobox_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_reservada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_calcularAFP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_calcularSFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_calcularISR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnAceptar1;
    private principal.MaterialButton btnSalir;
    private javax.swing.JCheckBox checkbox_calcularAFP;
    private javax.swing.JCheckBox checkbox_calcularISR;
    private javax.swing.JCheckBox checkbox_calcularSFS;
    private javax.swing.JCheckBox checkbox_reservada;
    private javax.swing.JComboBox<String> combobox_ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private principal.MaterialTextField txt_descripcion;
    private principal.MaterialTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
