/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisadcont.Panels;

import java.awt.BorderLayout;
import java.awt.Color;
import sisadcont.Forms.P_Principal;

public class P_Mod extends javax.swing.JPanel {

    /**
     * Creates new form P_Mod
     */
    public P_Mod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btn_6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btn_7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btn_8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btn_9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btn_10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btn_11 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btn_12 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btn_13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btn_14 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btn_15 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        btn_16 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btn_17 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btn_18 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        btn_19 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        btn_20 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        MiniPanel = new javax.swing.JPanel();
        btn_21 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        btn_22 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        btn_23 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        btn_24 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();

        btn_2.setBackground(new java.awt.Color(250, 106, 18));
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setToolTipText("");
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_2MouseReleased(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(250, 106, 18));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("FACTURACION");

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(5, 5, 5))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_4.setBackground(new java.awt.Color(250, 106, 18));
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setToolTipText("");
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_4MouseReleased(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(250, 106, 18));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventoario_icono.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("INVENTARIO");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(5, 5, 5))
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_5.setBackground(new java.awt.Color(250, 106, 18));
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setToolTipText("");
        btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_5MouseReleased(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(250, 106, 18));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank_card_dollar_24px.png"))); // NOI18N
        jLabel29.setMaximumSize(new java.awt.Dimension(26, 26));
        jLabel29.setPreferredSize(new java.awt.Dimension(26, 26));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CUENTAS X PAGAR");

        javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
        btn_5.setLayout(btn_5Layout);
        btn_5Layout.setHorizontalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_5Layout.setVerticalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_6.setBackground(new java.awt.Color(250, 106, 18));
        btn_6.setForeground(new java.awt.Color(255, 255, 255));
        btn_6.setToolTipText("");
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_6MouseReleased(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(250, 106, 18));
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/economic_improvement_24px.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("CONTABILIDAD");

        javax.swing.GroupLayout btn_6Layout = new javax.swing.GroupLayout(btn_6);
        btn_6.setLayout(btn_6Layout);
        btn_6Layout.setHorizontalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(5, 5, 5))
        );
        btn_6Layout.setVerticalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_7.setBackground(new java.awt.Color(250, 106, 18));
        btn_7.setForeground(new java.awt.Color(255, 255, 255));
        btn_7.setToolTipText("");
        btn_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_7MouseReleased(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(250, 106, 18));
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank_building_24px.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("BANCOS");

        javax.swing.GroupLayout btn_7Layout = new javax.swing.GroupLayout(btn_7);
        btn_7.setLayout(btn_7Layout);
        btn_7Layout.setHorizontalGroup(
            btn_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(5, 5, 5))
        );
        btn_7Layout.setVerticalGroup(
            btn_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_8.setBackground(new java.awt.Color(250, 106, 18));
        btn_8.setForeground(new java.awt.Color(255, 255, 255));
        btn_8.setToolTipText("");
        btn_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_8MouseReleased(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(250, 106, 18));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank_building_24px.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("MODULO FIJO ACTIVO");

        javax.swing.GroupLayout btn_8Layout = new javax.swing.GroupLayout(btn_8);
        btn_8.setLayout(btn_8Layout);
        btn_8Layout.setHorizontalGroup(
            btn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addGap(5, 5, 5))
        );
        btn_8Layout.setVerticalGroup(
            btn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_8Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_9.setBackground(new java.awt.Color(250, 106, 18));
        btn_9.setForeground(new java.awt.Color(255, 255, 255));
        btn_9.setToolTipText("");
        btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_9MouseReleased(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(250, 106, 18));
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formulario.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("FORMULARIOS DGII");

        javax.swing.GroupLayout btn_9Layout = new javax.swing.GroupLayout(btn_9);
        btn_9.setLayout(btn_9Layout);
        btn_9Layout.setHorizontalGroup(
            btn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(5, 5, 5))
        );
        btn_9Layout.setVerticalGroup(
            btn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_9Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_10.setBackground(new java.awt.Color(250, 106, 18));
        btn_10.setForeground(new java.awt.Color(255, 255, 255));
        btn_10.setToolTipText("");
        btn_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_10MouseReleased(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(250, 106, 18));
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("FACTURACION");

        javax.swing.GroupLayout btn_10Layout = new javax.swing.GroupLayout(btn_10);
        btn_10.setLayout(btn_10Layout);
        btn_10Layout.setHorizontalGroup(
            btn_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addGap(5, 5, 5))
        );
        btn_10Layout.setVerticalGroup(
            btn_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_10Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_11.setBackground(new java.awt.Color(250, 106, 18));
        btn_11.setForeground(new java.awt.Color(255, 255, 255));
        btn_11.setToolTipText("");
        btn_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_11MouseReleased(evt);
            }
        });

        jLabel41.setBackground(new java.awt.Color(250, 106, 18));
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cash_register_euro_24px.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("CAJAS");

        javax.swing.GroupLayout btn_11Layout = new javax.swing.GroupLayout(btn_11);
        btn_11.setLayout(btn_11Layout);
        btn_11Layout.setHorizontalGroup(
            btn_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(5, 5, 5))
        );
        btn_11Layout.setVerticalGroup(
            btn_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_11Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_12.setBackground(new java.awt.Color(250, 106, 18));
        btn_12.setForeground(new java.awt.Color(255, 255, 255));
        btn_12.setToolTipText("");
        btn_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_12MouseReleased(evt);
            }
        });

        jLabel43.setBackground(new java.awt.Color(250, 106, 18));
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("IMPRESORA FISCAL");

        javax.swing.GroupLayout btn_12Layout = new javax.swing.GroupLayout(btn_12);
        btn_12.setLayout(btn_12Layout);
        btn_12Layout.setHorizontalGroup(
            btn_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addGap(5, 5, 5))
        );
        btn_12Layout.setVerticalGroup(
            btn_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_12Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_13.setBackground(new java.awt.Color(250, 106, 18));
        btn_13.setForeground(new java.awt.Color(255, 255, 255));
        btn_13.setToolTipText("");
        btn_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_13MouseReleased(evt);
            }
        });

        jLabel45.setBackground(new java.awt.Color(250, 106, 18));
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maintenance_24px.png"))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("UTILIDADES");

        javax.swing.GroupLayout btn_13Layout = new javax.swing.GroupLayout(btn_13);
        btn_13.setLayout(btn_13Layout);
        btn_13Layout.setHorizontalGroup(
            btn_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addGap(5, 5, 5))
        );
        btn_13Layout.setVerticalGroup(
            btn_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_13Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_14.setBackground(new java.awt.Color(250, 106, 18));
        btn_14.setForeground(new java.awt.Color(255, 255, 255));
        btn_14.setToolTipText("");
        btn_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_14MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_14MouseReleased(evt);
            }
        });

        jLabel47.setBackground(new java.awt.Color(250, 106, 18));
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_24px.png"))); // NOI18N

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("CONFIGURACION");

        javax.swing.GroupLayout btn_14Layout = new javax.swing.GroupLayout(btn_14);
        btn_14.setLayout(btn_14Layout);
        btn_14Layout.setHorizontalGroup(
            btn_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addGap(5, 5, 5))
        );
        btn_14Layout.setVerticalGroup(
            btn_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_14Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_15.setBackground(new java.awt.Color(250, 106, 18));
        btn_15.setForeground(new java.awt.Color(255, 255, 255));
        btn_15.setToolTipText("");
        btn_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_15MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_15MouseReleased(evt);
            }
        });

        jLabel49.setBackground(new java.awt.Color(250, 106, 18));
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("FACTURACION");

        javax.swing.GroupLayout btn_15Layout = new javax.swing.GroupLayout(btn_15);
        btn_15.setLayout(btn_15Layout);
        btn_15Layout.setHorizontalGroup(
            btn_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addGap(5, 5, 5))
        );
        btn_15Layout.setVerticalGroup(
            btn_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_15Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_16.setBackground(new java.awt.Color(250, 106, 18));
        btn_16.setForeground(new java.awt.Color(255, 255, 255));
        btn_16.setToolTipText("");
        btn_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_16MouseReleased(evt);
            }
        });

        jLabel51.setBackground(new java.awt.Color(250, 106, 18));
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("FACTURACION");

        javax.swing.GroupLayout btn_16Layout = new javax.swing.GroupLayout(btn_16);
        btn_16.setLayout(btn_16Layout);
        btn_16Layout.setHorizontalGroup(
            btn_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addGap(5, 5, 5))
        );
        btn_16Layout.setVerticalGroup(
            btn_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_16Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_17.setBackground(new java.awt.Color(250, 106, 18));
        btn_17.setForeground(new java.awt.Color(255, 255, 255));
        btn_17.setToolTipText("");
        btn_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_17MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_17MouseReleased(evt);
            }
        });

        jLabel53.setBackground(new java.awt.Color(250, 106, 18));
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("FACTURACION");

        javax.swing.GroupLayout btn_17Layout = new javax.swing.GroupLayout(btn_17);
        btn_17.setLayout(btn_17Layout);
        btn_17Layout.setHorizontalGroup(
            btn_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addGap(5, 5, 5))
        );
        btn_17Layout.setVerticalGroup(
            btn_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_17Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_18.setBackground(new java.awt.Color(250, 106, 18));
        btn_18.setForeground(new java.awt.Color(255, 255, 255));
        btn_18.setToolTipText("");
        btn_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_18MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_18MouseReleased(evt);
            }
        });

        jLabel55.setBackground(new java.awt.Color(250, 106, 18));
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("FACTURACION");

        javax.swing.GroupLayout btn_18Layout = new javax.swing.GroupLayout(btn_18);
        btn_18.setLayout(btn_18Layout);
        btn_18Layout.setHorizontalGroup(
            btn_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addGap(5, 5, 5))
        );
        btn_18Layout.setVerticalGroup(
            btn_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_18Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_19.setBackground(new java.awt.Color(250, 106, 18));
        btn_19.setForeground(new java.awt.Color(255, 255, 255));
        btn_19.setToolTipText("");
        btn_19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_19MouseReleased(evt);
            }
        });

        jLabel57.setBackground(new java.awt.Color(250, 106, 18));
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("FACTURACION");

        javax.swing.GroupLayout btn_19Layout = new javax.swing.GroupLayout(btn_19);
        btn_19.setLayout(btn_19Layout);
        btn_19Layout.setHorizontalGroup(
            btn_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addGap(5, 5, 5))
        );
        btn_19Layout.setVerticalGroup(
            btn_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_19Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btn_20.setBackground(new java.awt.Color(250, 106, 18));
        btn_20.setForeground(new java.awt.Color(255, 255, 255));
        btn_20.setToolTipText("");
        btn_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_20MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_20MouseReleased(evt);
            }
        });

        jLabel59.setBackground(new java.awt.Color(250, 106, 18));
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("FACTURACION");

        javax.swing.GroupLayout btn_20Layout = new javax.swing.GroupLayout(btn_20);
        btn_20.setLayout(btn_20Layout);
        btn_20Layout.setHorizontalGroup(
            btn_20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel60)
                .addGap(5, 5, 5))
        );
        btn_20Layout.setVerticalGroup(
            btn_20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_20Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        MiniPanel.setBackground(new java.awt.Color(255, 255, 255));

        btn_21.setBackground(new java.awt.Color(250, 106, 18));
        btn_21.setForeground(new java.awt.Color(255, 255, 255));
        btn_21.setToolTipText("");
        btn_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_21MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_21MouseReleased(evt);
            }
        });
        btn_21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_21KeyPressed(evt);
            }
        });

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        javax.swing.GroupLayout btn_21Layout = new javax.swing.GroupLayout(btn_21);
        btn_21.setLayout(btn_21Layout);
        btn_21Layout.setHorizontalGroup(
            btn_21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel61)
                .addGap(10, 10, 10))
        );
        btn_21Layout.setVerticalGroup(
            btn_21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_21Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel61))
        );

        btn_22.setBackground(new java.awt.Color(250, 106, 18));
        btn_22.setForeground(new java.awt.Color(255, 255, 255));
        btn_22.setToolTipText("");
        btn_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_22MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_22MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_22MouseReleased(evt);
            }
        });
        btn_22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_22KeyPressed(evt);
            }
        });

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N

        javax.swing.GroupLayout btn_22Layout = new javax.swing.GroupLayout(btn_22);
        btn_22.setLayout(btn_22Layout);
        btn_22Layout.setHorizontalGroup(
            btn_22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_22Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel62)
                .addGap(10, 10, 10))
        );
        btn_22Layout.setVerticalGroup(
            btn_22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_22Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel62))
        );

        btn_23.setBackground(new java.awt.Color(250, 106, 18));
        btn_23.setForeground(new java.awt.Color(255, 255, 255));
        btn_23.setToolTipText("");
        btn_23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_23MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_23MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_23MouseReleased(evt);
            }
        });
        btn_23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_23KeyPressed(evt);
            }
        });

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warehouse_1_24px.png"))); // NOI18N

        javax.swing.GroupLayout btn_23Layout = new javax.swing.GroupLayout(btn_23);
        btn_23.setLayout(btn_23Layout);
        btn_23Layout.setHorizontalGroup(
            btn_23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel63)
                .addGap(10, 10, 10))
        );
        btn_23Layout.setVerticalGroup(
            btn_23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_23Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel63))
        );

        btn_24.setBackground(new java.awt.Color(250, 106, 18));
        btn_24.setForeground(new java.awt.Color(255, 255, 255));
        btn_24.setToolTipText("");
        btn_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_24MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_24MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_24MouseReleased(evt);
            }
        });
        btn_24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_24KeyPressed(evt);
            }
        });

        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N

        javax.swing.GroupLayout btn_24Layout = new javax.swing.GroupLayout(btn_24);
        btn_24.setLayout(btn_24Layout);
        btn_24Layout.setHorizontalGroup(
            btn_24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_24Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel64)
                .addGap(10, 10, 10))
        );
        btn_24Layout.setVerticalGroup(
            btn_24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_24Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel64))
        );

        javax.swing.GroupLayout MiniPanelLayout = new javax.swing.GroupLayout(MiniPanel);
        MiniPanel.setLayout(MiniPanelLayout);
        MiniPanelLayout.setHorizontalGroup(
            MiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        MiniPanelLayout.setVerticalGroup(
            MiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(306, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MiniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseClicked
/*
        Paneles.setSize(1020, 600);
        //Paneles.setLocation (0,0);

        Paneles.removeAll();
        //Paneles.add(Paneles,BorderLayout.CENTER);
        //Paneles.revalidate();
        Paneles.repaint();

        Ter_panel.setSize(1020, 52);
        //Ter_panel.setLocation (0,0);

        Ter_panel.removeAll();
        //Paneles.add(Paneles,BorderLayout.CENTER);
        //Paneles.revalidate();
        Ter_panel.repaint();*/
    }//GEN-LAST:event_btn_2MouseClicked

    private void btn_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseEntered
        // TODO add your handling code here:

        btn_2.setBackground(new Color(250,70,18));

    }//GEN-LAST:event_btn_2MouseEntered

    private void btn_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseExited
        // TODO add your handling code here:
        btn_2.setBackground(new Color(250,106,18));
    }//GEN-LAST:event_btn_2MouseExited

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2MousePressed

    private void btn_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2MouseReleased

    private void btn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MouseClicked

    private void btn_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MouseEntered

    private void btn_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MouseExited

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MouseReleased

    private void btn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseClicked

    private void btn_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseEntered

    private void btn_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseExited

    private void btn_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseReleased

    private void btn_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MouseClicked

    private void btn_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MouseEntered

    private void btn_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MouseExited

    private void btn_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MousePressed

    private void btn_6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MouseReleased

    private void btn_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MouseClicked

    private void btn_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MouseEntered

    private void btn_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MouseExited

    private void btn_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MousePressed

    private void btn_7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MouseReleased

    private void btn_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MouseClicked

    private void btn_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MouseEntered

    private void btn_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MouseExited

    private void btn_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MousePressed

    private void btn_8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MouseReleased

    private void btn_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9MouseClicked

    private void btn_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9MouseEntered

    private void btn_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9MouseExited

    private void btn_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9MousePressed

    private void btn_9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9MouseReleased

    private void btn_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_10MouseClicked

    private void btn_10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_10MouseEntered

    private void btn_10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_10MouseExited

    private void btn_10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_10MousePressed

    private void btn_10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_10MouseReleased

    private void btn_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11MouseClicked

    private void btn_11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11MouseEntered

    private void btn_11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11MouseExited

    private void btn_11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11MousePressed

    private void btn_11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_11MouseReleased

    private void btn_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12MouseClicked

    private void btn_12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12MouseEntered

    private void btn_12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12MouseExited

    private void btn_12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12MousePressed

    private void btn_12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_12MouseReleased

    private void btn_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13MouseClicked

    private void btn_13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13MouseEntered

    private void btn_13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13MouseExited

    private void btn_13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13MousePressed

    private void btn_13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_13MouseReleased

    private void btn_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14MouseClicked

    private void btn_14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14MouseEntered

    private void btn_14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14MouseExited

    private void btn_14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14MousePressed

    private void btn_14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_14MouseReleased

    private void btn_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15MouseClicked

    private void btn_15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15MouseEntered

    private void btn_15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15MouseExited

    private void btn_15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15MousePressed

    private void btn_15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_15MouseReleased

    private void btn_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_16MouseClicked

    private void btn_16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_16MouseEntered

    private void btn_16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_16MouseExited

    private void btn_16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_16MousePressed

    private void btn_16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_16MouseReleased

    private void btn_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_17MouseClicked

    private void btn_17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_17MouseEntered

    private void btn_17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_17MouseExited

    private void btn_17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_17MousePressed

    private void btn_17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_17MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_17MouseReleased

    private void btn_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_18MouseClicked

    private void btn_18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_18MouseEntered

    private void btn_18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_18MouseExited

    private void btn_18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_18MousePressed

    private void btn_18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_18MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_18MouseReleased

    private void btn_19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_19MouseClicked

    private void btn_19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_19MouseEntered

    private void btn_19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_19MouseExited

    private void btn_19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_19MousePressed

    private void btn_19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_19MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_19MouseReleased

    private void btn_20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_20MouseClicked

    private void btn_20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_20MouseEntered

    private void btn_20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_20MouseExited

    private void btn_20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_20MousePressed

    private void btn_20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_20MouseReleased

    private void btn_21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MouseClicked
        // TODO add your handling code here:

        P_Principal.Sec_panel.setVisible(true);
        P_Mod.MiniPanel.setSize(256, 38);
        P_Mod.MiniPanel.setLocation (0,0);

        P_Principal.Mini_Panel.removeAll();
        P_Principal.Mini_Panel.add(P_Mod.MiniPanel,BorderLayout.CENTER);
        P_Principal.Mini_Panel.revalidate();
        P_Principal.Mini_Panel.repaint();

    }//GEN-LAST:event_btn_21MouseClicked

    private void btn_21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21MouseEntered

    private void btn_21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21MouseExited

    private void btn_21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21MousePressed

    private void btn_21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_21MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21MouseReleased

    private void btn_21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_21KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_21KeyPressed

    private void btn_22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22MouseClicked

    private void btn_22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22MouseEntered

    private void btn_22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22MouseExited

    private void btn_22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22MousePressed

    private void btn_22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_22MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22MouseReleased

    private void btn_22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_22KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_22KeyPressed

    private void btn_23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23MouseClicked

    private void btn_23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23MouseEntered

    private void btn_23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_23MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23MouseExited

    private void btn_23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_23MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23MousePressed

    private void btn_23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_23MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23MouseReleased

    private void btn_23KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_23KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_23KeyPressed

    private void btn_24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24MouseClicked

    private void btn_24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_24MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24MouseEntered

    private void btn_24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_24MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24MouseExited

    private void btn_24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_24MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24MousePressed

    private void btn_24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_24MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24MouseReleased

    private void btn_24KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_24KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_24KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel MiniPanel;
    public static javax.swing.JPanel btn_10;
    public static javax.swing.JPanel btn_11;
    public static javax.swing.JPanel btn_12;
    public static javax.swing.JPanel btn_13;
    public static javax.swing.JPanel btn_14;
    public static javax.swing.JPanel btn_15;
    public static javax.swing.JPanel btn_16;
    public static javax.swing.JPanel btn_17;
    public static javax.swing.JPanel btn_18;
    public static javax.swing.JPanel btn_19;
    public static javax.swing.JPanel btn_2;
    public static javax.swing.JPanel btn_20;
    public static javax.swing.JPanel btn_21;
    public static javax.swing.JPanel btn_22;
    public static javax.swing.JPanel btn_23;
    public static javax.swing.JPanel btn_24;
    public static javax.swing.JPanel btn_4;
    public static javax.swing.JPanel btn_5;
    public static javax.swing.JPanel btn_6;
    public static javax.swing.JPanel btn_7;
    public static javax.swing.JPanel btn_8;
    public static javax.swing.JPanel btn_9;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    // End of variables declaration//GEN-END:variables
}
